Develeop
amnona/calour pull request #30
Opened 2017-02-22 22:06 UTC by amnona

update info in gui when new feature/sample field selected
create AmpliconExperiment subclass
remove unneeded functions in analysis.py

2017-02-23 00:05 UTC, RNAer requested changes

2017-02-23 00:05 UTC, RNAer commented on calour/amplicon_experiment.py
> +        ``Experiment``
AmpliconExperiment

2017-02-23 00:05 UTC, RNAer commented on calour/heatmap/plotgui.py
> +        abundance : numeric
the original way is the correct style for doc

2017-02-23 00:05 UTC, RNAer commented on calour/io.py
>      exp.feature_metadata.index = exp.feature_metadata.index.str.upper()
why `upper`?

2017-02-23 00:05 UTC, RNAer commented on calour/tests/test_amplicon_experiment.py
> +        self.assertIn(self.test1.feature_metadata.index[5], exp.feature_metadata.index)
instead of `In` and `NotIn`, why not just do similarly as you did in line 29

2017-02-23 00:05 UTC, RNAer commented on calour/tests/test_amplicon_experiment.py
> +        # and is not inplace
comment is incorrect

2017-02-23 00:23 UTC, amnona commented on calour/amplicon_experiment.py
> +        ``Experiment``
fixed

2017-02-23 00:24 UTC, amnona commented on calour/io.py
>      exp.feature_metadata.index = exp.feature_metadata.index.str.upper()
to prevent uppercase/lowercase problems in comparison. we convert all sequences to upper

2017-02-23 00:26 UTC, amnona commented on calour/tests/test_amplicon_experiment.py
> +        self.assertIn(self.test1.feature_metadata.index[5], exp.feature_metadata.index)
too many sequences (we are using negate, so we have 6 sequences left). i'm lazy

2017-02-23 00:26 UTC, amnona commented on calour/tests/test_amplicon_experiment.py
> +        # and is not inplace
fixed

2017-02-23 00:29 UTC, amnona commented on calour/heatmap/plotgui.py
> +        abundance : numeric
fixed

2017-02-24 00:19 UTC, RNAer commented
@amnona is it ready for review? or you are gonna make more changes?

2017-02-24 00:24 UTC, amnona commented
now it is ready :)
got rid of almost all cahelper functions!
moving further work to a different branch


On Thu, Feb 23, 2017 at 4:19 PM, Zech Xu <notifications@github.com> wrote:

> @amnona <https://github.com/amnona> is it ready for review? or you are
> gonna make more changes?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/amnona/calour/pull/30#issuecomment-282164877>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AFkA8uKRj2PWMbgLeQHh9t1xRl-5YCEAks5rfiH6gaJpZM4MJQL8>
> .
>

2017-02-24 23:07 UTC, RNAer requested changes

2017-02-24 23:07 UTC, RNAer commented on calour/sorting.py
> +def sort_freq(exp, field=None, value=None, inplace=False, **kwargs):
-> `sort_abundance`

2017-02-24 23:07 UTC, RNAer commented on calour/sorting.py
> +def cluster_features(exp, minreads=10, inplace=False, **kwargs):
change `minreads` to `min_abund`?

2017-02-24 23:07 UTC, RNAer commented on calour/tests/test_amplicon_experiment.py
> +        npt.assert_array_equal(data[:, :], orig_data[:, okseqs])
delete `[:, :]`

2017-02-24 23:07 UTC, RNAer commented on calour/tests/test_analysis.py
> +        self.assertCountEqual(enriched, ['a', 'e'])
compare all the values in `res`

2017-02-24 23:08 UTC, amnona commented on calour/sorting.py
> +def sort_freq(exp, field=None, value=None, inplace=False, **kwargs):
done

2017-02-24 23:08 UTC, amnona commented on calour/sorting.py
> +def cluster_features(exp, minreads=10, inplace=False, **kwargs):
done

2017-02-24 23:09 UTC, amnona commented on calour/tests/test_amplicon_experiment.py
> +        npt.assert_array_equal(data[:, :], orig_data[:, okseqs])
done

2017-02-24 23:27 UTC, merged