lots of goodies
amnona/calour pull request #49
Opened 2017-03-30 23:38 UTC by amnona

- interactive html export of heatmap
- faster sum/mean for filtering
- move analysis into database modules

2017-04-04 23:21 UTC, RNAer requested changes

2017-04-04 23:21 UTC, RNAer commented on calour/filtering.py
> +                'mean_abundance': _mean_abundance,
delete `sum_abundance` and `mean_abundance`

2017-04-04 23:21 UTC, RNAer commented on calour/transforming.py
> +    '''Normalize each sample by ignoring the features with mean>=min_frac in all the experiment
add an blanke line

2017-04-04 23:21 UTC, RNAer commented on calour/transforming.py
> +    newexp = exp.normalize_by_subset_features(comp_features.feature_metadata.index.values, total=total, negate=True, inplace=inplace)
line too long!

2017-04-04 23:21 UTC, RNAer commented on calour/heatmap/plotgui_qt5.py
> +        exp = self.gui.exp
document this func

2017-04-04 23:21 UTC, RNAer commented on calour/heatmap/plotgui_qt5.py
>          group2_seqs = list(set(allseqs).difference(set(group1_seqs)))
use `set1 - set2`, which is more clear

2017-04-04 23:21 UTC, RNAer commented on calour/export_html.py
> +    '''Convert a list to a string representation of the list
why not just `repr(a_list)`?

2017-04-04 23:21 UTC, RNAer commented on calour/export_html.py
> +    figfile.close()
use `with`

2017-04-04 23:21 UTC, RNAer commented on calour/export_html.py
> +    html_page = html_page.replace('**image_goes_here**', urllib.parse.quote(figdata_png))
mv `urllib.parse.quote` to `with` block. just use the final value in this `replace` call

2017-04-05 00:05 UTC, amnona commented on calour/filtering.py
> +                'mean_abundance': _mean_abundance,
yes :)

2017-04-05 00:06 UTC, amnona commented on calour/transforming.py
> +    '''Normalize each sample by ignoring the features with mean>=min_frac in all the experiment
done

2017-04-05 00:07 UTC, amnona commented on calour/transforming.py
> +    newexp = exp.normalize_by_subset_features(comp_features.feature_metadata.index.values, total=total, negate=True, inplace=inplace)
ok

2017-04-05 00:10 UTC, amnona commented on calour/heatmap/plotgui_qt5.py
> +        exp = self.gui.exp
done

2017-04-05 00:11 UTC, amnona commented on calour/heatmap/plotgui_qt5.py
>          group2_seqs = list(set(allseqs).difference(set(group1_seqs)))
ok

2017-04-05 00:18 UTC, amnona commented on calour/export_html.py
> +    '''Convert a list to a string representation of the list
never

2017-04-05 00:21 UTC, amnona commented on calour/export_html.py
> +    figfile.close()
done by you :)

2017-04-05 00:21 UTC, amnona commented on calour/export_html.py
> +    html_page = html_page.replace('**image_goes_here**', urllib.parse.quote(figdata_png))
done by you :)

2017-04-05 00:30 UTC, RNAer requested changes

2017-04-05 00:30 UTC, RNAer commented on calour/heatmap/plotgui_qt5.py
> +        group2_seqs = list(set(allseqs) - set(group1_seqs))
no need to convert to list

2017-04-05 00:36 UTC, amnona commented on calour/heatmap/plotgui_qt5.py
> +        group2_seqs = list(set(allseqs) - set(group1_seqs))
true :)

2017-04-05 00:37 UTC, merged